database:
  name: "survival"

discord:
  message: "&6&l» &7Join our Discord server: &6discord.gg/yzj9HrF"
  link: "https://discord.gg/yzj9HrF"

vote:
  message: "&6&l» &7Vote at &6https://git.io/Jew2k&7. You've voted &6[votes] &7times."
  link: "https://git.io/Jew2k"

playtime:
  border: "&r&m&l━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  playtime: "&7Playtime: &6[playtime]\n"
  joined: "&7Join date: &6[joined]\n"