name: Ember
version: 3.0
author: TechToolbox (@nkomarn)
main: xyz.nkomarn.Ember.Ember
description: The core for Firestarter proxies!
website: https://firestartermc.com/opensource
api-version: 1.15
depend: ['Votifier']

commands:
  discord:
    description: "View the Discord server invite."
  reddit:
    description: "Visit the Reddit community."
  vote:
    description: "View the amount of times you have voted as well as the vote link."
  playtime:
    description: "View the total amount of time you have spent playing on Firestarter!"
    aliases: ["played", "joined"]